# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .alias import *
from .domain import *
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_improvmx.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_improvmx.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "improvmx",
  "mod": "index",
  "fqn": "pulumi_improvmx",
  "classes": {
   "improvmx:index:Alias": "Alias",
   "improvmx:index:Domain": "Domain"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "improvmx",
  "token": "pulumi:providers:improvmx",
  "fqn": "pulumi_improvmx",
  "class": "Provider"
 }
]
"""
)
