// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace Pulumi.Improvmx
{
    public static class Config
    {
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("improvmx");

        private static readonly __Value<string?> _api_key = new __Value<string?>(() => __config.Get("api_key"));
        /// <summary>
        /// API key for the ImprovMX
        /// </summary>
        public static string? Api_key
        {
            get => _api_key.Get();
            set => _api_key.Set(value);
        }

        private static readonly __Value<string?> _version = new __Value<string?>(() => __config.Get("version"));
        public static string? Version
        {
            get => _version.Get();
            set => _version.Set(value);
        }

    }
}
